apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector: { matchLabels: { app: redis } }
  template:
    metadata: { labels: { app: redis } }
    spec:
      containers: [ { name: redis, image: redis } ]
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports: [ { name: "redis", port: 6379, targetPort: 6379 } ]
  selector: { app: redis }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasher
spec:
  selector: { matchLabels: { app: hasher } }
  template:
    metadata: { labels: { app: hasher } }
    spec:
      containers: [ { name: hasher, image: dockercoins/hasher:v0.1 } ]
---
apiVersion: v1
kind: Service
metadata:
  name: hasher
spec:
  ports: [ { name: "http", port: 80, targetPort: 80 } ]
  selector: { app: hasher }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rng
spec:
  selector: { matchLabels: { app: rng } }
  template:
    metadata: { labels: { app: rng } }
    spec:
      containers: [ { name: rng, image: dockercoins/rng:v0.1 } ]
---
apiVersion: v1
kind: Service
metadata:
  name: rng
spec:
  ports: [ { name: "http", port: 80, targetPort: 80 } ]
  selector: { app: rng }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
spec:
  selector: { matchLabels: { app: webui } }
  template:
    metadata: { labels: { app: webui } }
    spec:
      containers: [ { name: webui, image: dockercoins/webui:v0.1 } ]
---
apiVersion: v1
kind: Service
metadata:
  name: webui
spec:
  type: LoadBalancer
  ports: [ { name: "http", port: 8081, targetPort: 80 } ]
  selector: { app: webui }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  selector: { matchLabels: { app: worker } }
  template:
    metadata: { labels: { app: worker } }
    spec:
      containers: [ { name: worker, image: dockercoins/worker:v0.1 } ]
