apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rng
  labels:
    app: rng
spec:
  selector:
    matchLabels:
      app: rng
  template:
    metadata:
      labels:
        app: rng
    spec:
      containers:
      - name: rng
        image: dockercoins/rng:v0.1
